
var headerText = "Bingo";

var footerText = "<a href='https://github.com/andir/HTML5-bingo/' target='_blank'>Code available on github</a>";

var winText = "Winner";

var clickSnd = new Audio("audio/click.mp3");

var winSnd = new Audio("audio/win.mp3");

var JSONBingo = {"squares": [
        {"square": "Kompetenzteam"},
        {"square": "Web-Team"},
        {"square": "Taiga"},
        {"square": "Barcamp"},
        {"square": "Commnity-Team"},
        {"square": "NOC"},
        {"square": "GW02"},
        {"square": "LaDaDi"},
        {"square": "Freifunk-GmbH"},
        {"square": "Sprachregelung"},
        {"square": "Freifunk-Initiative"},
        {"square": "Cyber"},
        {"square": "PoE-Extreme"},
        {"square": "Ticket"},
        {"square": "Beseb"},
        {"square": "Consulting"},
        {"square": "Telekom"},
        {"square": "HEAG Medianet"},
        {"square": "*Pizza wird geliefert*"},
        {"square": "Goddelau"},
        {"square": "Starkenburg"},
        {"square": "Jefferson"},
        {"square": "(Glas-)Faser"},
        {"square": "LTE"},
        {"square": "bereitstellen"},
        {"square": "*MisterY betritt den Raum*"},
        {"square": "Flyer"},
        {"square": "Richtfunk"},
        {"square": "841er"},
        {"square": "direkt abfackeln"},
        {"square": "Poolgeraete"},
        {"square": "Core-Freifunk"},
        {"square": "QoS"},
        {"square": "Amateurfunker"},
        {"square": "Hochhaus / HDA-Turm"},
        {"square": "*md appears*"},
        {"square": "mitwirken"},
        {"square": "Linkstrecke"},
        {"square": "heute wenig Zeit"},
        {"square": "Latino"},
        {"square": "ueberparteilich"},
        {"square": "Stakeholder"},
        {"square": "hexa informiert"},
        {"square": "hexa ist Freifunk"},
        {"square": "IRC"},
        {"square": "beseb war Radfahren"},
        {"square": "Freifunk Verein"},
        {"square": "1500 Fluechtlinge"},
        {"square": "RP-Darmstadt"},
        {"square": "Eingeladen"},
        {"square": "Verbaende"},
        {"square": "Outreach"},
        {"square": "Expertenrunde"},
        {"square": "Bergstrasse"},
        {"square": "*Schoko-Banane-Riegel*"},
        {"square": "Bensheim"},
        {"square": "Infoveranstaltung"},
        {"square": "Perspektive"},
        {"square": "bestpractice"},
        {"square": "Nazco"},
        {"square": "alles anzuenden"},
        {"square": "Backbone"},
        {"square": "MANDA"},
        {"square": "100 MEEEEGAABIT"},
        {"square": "Uplink"},
        {"square": "Gipfeltreffen"},
        {"square": "Förderverein Freie Netz(e|werke) e.V."},
        {"square": "Journalist"},
        {"square": "fertiger Artikel"},
        {"square": "*Jemand hat ein Bingo*"},
        {"square": "ffda-intern"},
        {"square": "Finanzmittel"},
        {"square": "Kooperation"},
        {"square": "Plen(i|a)"},
        {"square": "CPE"},
        {"square": "UBNT"},
        {"square": "Webscale"},
        {"square": "MongoDB"},
        {"square": "NodeJS"},
        {"square": "Offloader"},
        {"square": "Hotspot"},
        {"square": "Null-Cipher"},
        {"square": "Transportverschlüsselung"}"
    ]
};
